#!/usr/bin/env sh

regex='\(\[colors-schema\]: macros/colors-table.fnl#L\)\([0-9]*\)'

schema_nr="$(awk '/set M.schema/ { print NR }' macros/colors-table.fnl)"
old_schema_nr="$(sed -n 's|'"$regex"'|\2|p' CONTRIBUTING.md)"

if [ "$schema_nr" = "$old_schema_nr" ]; then
	echo 'Schema line number is already correct'
else
	sed -i 's|'"$regex"'|\1'"$schema_nr"'|' CONTRIBUTING.md
	echo "Updated schema line number from '$old_schema_nr' to '$schema_nr'"
fi
